config/routes.rb
Rails.application.routes.draw do
  namespace :api do
   namespace :v1 do
    resources :devices
    resources :statuses
   end
  end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
    render json: @devices
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    render json: @device, status: :ok
  end

  # GET /devices/1/edit
  def edit
    device = Device.find(params[:id])
    if device.update(device_params)
      render json: device, status: :ok
    else
      render json: { errors: device.errors }, status: :unprocessable_entity
    end
  end

  # POST /devices
  # POST /devices.json
  def create
    device = Device.new(device_params)
      if device.save
        render json: device, status: :created
      else
        render json: {errors: device.errors}, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    device = Device.find(params[:id])
    if device.update(device_params)
      render json: device, status: :ok
    else
      render json: { errors: device.errors }, status: :unprocessable_entity
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    head 204
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:deviceId, :message)
    end
end

app/controllers/api/v1/statuses_controller.rb
class Api::V1::StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
    render json: @statuses
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    status = Status.find(params[:id])
    if status.update(status_params)
      render json: status, status: :ok
    else
      render json: { errors: status.errors }, status: :unprocessable_entity
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:isActive)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deviceId %>
    <%= form.text_field :deviceId %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Deviceid</th>
      <th>Integer</th>
      <th>Message</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.deviceId %></td>
        <td><%= device.integer %></td>
        <td><%= device.message %></td>
        <td><%= device.string %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deviceid:</strong>
  <%= @device.deviceId %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @device.integer %>
</p>

<p>
  <strong>Message:</strong>
  <%= @device.message %>
</p>

<p>
  <strong>String:</strong>
  <%= @device.string %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roomates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isActive %>
    <%= form.text_field :isActive %>
  </div>

  <div class="field">
    <%= form.label :boolean %>
    <%= form.text_field :boolean %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Isactive</th>
      <th>Boolean</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.isActive %></td>
        <td><%= status.boolean %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isactive:</strong>
  <%= @status.isActive %>
</p>

<p>
  <strong>Boolean:</strong>
  <%= @status.boolean %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>